name: package-linters

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt
      - name: Run linters
        run: |
          isort --check pymath_tools unittests setup.py
          black --check pymath_tools unittests setup.py
          pip install .
          flake8 --tee --format=pylint unittests pymath_tools
          pylint --rcfile=pylintrc pymath_tools unittests
